# See .env to set useful environment vars

services:
  db:
    image: postgres:16
    container_name: "${APP_NAME}-db"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${APP_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${APP_NAME}", "-U", "${APP_NAME}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    # uncomment if you want to directly access your db for querying...
    # Change port if necessary, e.g. if you host already exposes another postgres container on the same port
    # ports:
    #  - "5433:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7
    container_name: "${APP_NAME}-redis"
    restart: unless-stopped
    # uncomment if you want to directly access your redis container for data visualization...
    # Change port if necessary, e.g. if you host already exposes another redis container on the same port
    # ports:
    #  - "6379:6379"
    networks:
      - default

  app:
    # allow linux hosts to resolve host.docker.internal
    extra_hosts:
      - "host.docker.internal=host-gateway"
    build:
      context: ../..
      dockerfile: docker/dev/frankenphp/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        DOCKER_GID: ${DOCKER_GID:-1001}
        APP_USER: ${APP_USER:-symfony}
    container_name: "${APP_NAME}-web"
    restart: unless-stopped

    # For Windows (WSl) or if you are unable to pass the actual docker group id DOCKER_GID arg
    # Running as root allows changing /var/run/docker.sock ownership so that TestContainers can work
    # the app will then run as ${APP_USER}
    user: root
    volumes:
      # Mounting files / directories separately for performance on windows hosts
      - ../../symfony/src:/app/src
      - ../../symfony/tests:/app/tests
      - ../../symfony/config:/app/config
      - ../../symfony/coverage:/app/coverage
      - ../../symfony/migrations:/app/migrations
      - ../../symfony/templates:/app/templates
      - ../../symfony/public:/app/public
      - ../../symfony/composer.json:/app/composer.json
      - ../../symfony/composer.lock:/app/composer.lock
      - ../../symfony/.env:/app/.env
      - ../../symfony/.env.dev:/app/.env.dev
      - ../../symfony/.env.test:/app/.env.test
      - ../../symfony/phpunit.xml:/app/phpunit.xml

      # Mounting the vendor directory as a volume on a Windows host results in major performance issues
      # You can uncomment this line if you host runs on linux or macOS
      # If your host runs under windows, not mounting vendor implies that all composer update/install/require commands
      # must be run both in the container and in the host if you want your IDE to be able to browse the vendor dir (for autocomplete...)
      # - ../../symfony/vendor:/app/vendor

      # Windows (WSL) / Linux
      # Mounting docker socket is necessary to enable TestContainers to create containers
      # On windows hosts, you may be able to comment this line, expose the docker API via TCP in Docker Desktop
      # and then set DOCKER_HOST env variable, although it's not recommended
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CONFIG=client_host=host.docker.internal

      # macOS (UNTESTED): it seems that to allow Testcontainers to create containers, the docker API should be exposed through TCP
      # in Docker Desktop
      # Then the DOCKER_HOST var below should be set (change port if necessary)
      # DOCKER_HOST: tcp://host.docker.internal:2375

    ports:
      - "8080:80"   # FrankenPHP
    depends_on:
      - db
      - redis
    networks:
      - default

volumes:
  db_data:

networks:
  default:
    driver: bridge