# See .env to set useful environment vars

services:

  app:
    image: app-ci:latest
    extra_hosts:
      - "host.docker.internal=host-gateway"
    container_name: "${APP_NAME}-ci"
    restart: unless-stopped
    user: root
    volumes:
      - ../../symfony:/app
      # Mounting docker socket to allow TestContainers to create containers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CONFIG=client_host=host.docker.internal