name: CI

concurrency:
  group: ${{ github.ref }}.ci
  cancel-in-progress: true
on:
  # CI should be able to run manually
  # which will be interpreted as a push on main
  workflow_dispatch:
  # CI should run on pull requests and push on main branch
  # some steps are executed only on pushes on main branch
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  backend-tests:
    name: Run backend tests and publish coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose -f docker/dev/docker-compose.yml build --no-cache

      - name: Start services
        run: docker compose -f docker/dev/docker-compose.yml up -d

      - name: Execude tests inside container
        run: docker compose exec -T php vendor/bin/phpunit --coverage-text --min-coverage=80

      - name: Stop services
        if: always()
        run: docker compose -f docker/dev/docker-compose.yml down -v