name: CI for Symfony

concurrency:
  group: ${{ github.ref }}.ci
  cancel-in-progress: true
on:
  # CI should be able to run manually
  # which will be interpreted as a push on main
  workflow_dispatch:
  # CI should run on pull requests and push on main branch
  # some steps are executed only on pushes on main branch
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build:
    name: Build CI image using caches
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: docker/ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare symfony environment
        working-directory: symfony
        run: |
          cp .env.test.dist .env.test

      - name: Check current directory and list files
        run: |
          echo "Current directory:"
          pwd
          echo "Files here:"
          ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Buildx layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-

      - name: Cache Composer (host cache - helps local composer if used)
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('symfony/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: set-tag
        run: |
          TAG=ci-${GITHUB_SHA}
          echo "image-tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build with buildx
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/docker/ci/frankenphp/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.image-tag }},${{ env.IMAGE_NAME }}:ci-latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    defaults:
      run:
        working-directory: docker/ci

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull CI image
        run: docker pull ${{ env.IMAGE_NAME }}:ci-${{ needs.build.outputs.image-tag }}

      - name: Start services
        run: docker compose  up -d

      - name: Run tests with coverage
        id: run-tests
        run: docker compose exec -T app composer test
        continue-on-error: true

      - name: Upload symfony coverage report artifact
        uses: actions/upload-artifact@v5
        with:
          name: symfony-coverage
          path: symfony/coverage
          retention-days: 7

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: symfony
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SYMFONY }}

      - name: SonarQube Quality Gate Check
        id: quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SYMFONY }}
        continue-on-error: true

      - name: Stop services
        if: always()
        run: docker compose down -v

      # fail job if coverage or quality requirements not met
      # this allows to explicitly specify what went wrong, as we used continue-on-error previously
      - name: Check requirements
        if: ${{ steps.run-tests.outcome == 'failure' || steps.quality-gate.outcome == 'failure' }}
        run: |
          echo "Job failed :"
          if [ "${{ steps.run-tests.outcome }}" == "failure" ]; then
            echo "Coverage checks have not been met. See step 'Run tests with coverage' output, and coverage report"
          fi
          if [ "${{ steps.quality-gate.outcome }}" == "failure" ]; then
            echo "Code quality gate check failed. See step 'SonarQube Quality Gate Check'"
          fi
          exit 1

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: symfony

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo_pgsql, redis, intl, zip

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan

      - name: Upload PHPStan report (optional)
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: phpstan-report
          path: phpstan-report.txt