name: CI for Symfony

concurrency:
  group: ${{ github.ref }}.ci
  cancel-in-progress: true
on:
  # CI should be able to run manually
  # which will be interpreted as a push on main
  workflow_dispatch:
  # CI should run on pull requests and push on main branch
  # some steps are executed only on pushes on main branch
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup project
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: symfony

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: intl, pdo_pgsql, redis, zip

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Upload vendor
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: symfony/vendor

  test:
    name: Run tests with coverage
    runs-on: ubuntu-latest
    needs: setup
    env:
      TESTCONTAINERS_HOST: 127.0.0.1

    defaults:
      run:
        working-directory: symfony

    steps:
      - uses: actions/checkout@v4

      - name: Prepare symfony environment
        run: |
          cp .env.test.dist .env.test

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: intl, pdo_pgsql, redis, zip
          coverage: xdebug

      - name: Download vendor
        uses: actions/download-artifact@v6
        with:
          name: vendor
          path: symfony/vendor

      - name: Fix executable permissions
        run: chmod +x vendor/bin/phpunit vendor/bin/coverage-check

      - name: Run tests with coverage
        id: run-tests
        run: composer test
        # this step may fail if minimum coverage is not reached, but we need do continue anyway
        # because we need to update coverage report and run sonar scan later
        continue-on-error: true

      # if coverage doesn't exist, something bad happened, and we can't go further
      - name: Verify coverage report existence and stop if missing
        run: |
          if [ ! -f "./coverage/clover.xml" ]; then          
           echo "Error: File 'symfony/coverage/clover.xml' not found. Job failed."
           exit 1
          fi
        shell: bash

      - name: Upload symfony coverage report artifact
        uses: actions/upload-artifact@v5
        with:
          name: symfony-coverage
          path: symfony/coverage
          retention-days: 7

  analysis:
    name: Static analysis with phpstan
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: symfony

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo_pgsql, redis, intl, zip

      - name: Download vendor
        uses: actions/download-artifact@v6
        with:
          name: vendor
          path: symfony/vendor

      - name: Fix executable permissions
        run: chmod +x vendor/bin/phpstan

      - name: Run PHPStan
        run: vendor/bin/phpstan > phpstan-report.txt || true

      - name: Upload PHPStan report (optional)
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: phpstan-report
          path: symfony/phpstan-report.txt
          retention-days: 7

  quality:
    name: Sonar Scan analysis + quality gate
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: symfony

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage
        uses: actions/download-artifact@v6
        with:
          name: symfony-coverage
          path: symfony/coverage

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: symfony
          args: >
            -Dsonar.branch.name=${{ github.ref_name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SYMFONY }}

      - name: Check current directory and list files
        run: |
          echo "Current directory:"
          pwd
          echo "Files here:"
          ls -la
          echo "Files in scannerwork : "
          ls -la .scannerwork
        continue-on-error: true

      - name: SonarQube Quality Gate Check
        id: quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: symfony/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SYMFONY }}